### ISSUE TITLE
Add macOS platform

### ISSUE THREAD

**Issue by saket** [saket/press#10]
The shared module currently only has Android and iOS platform targets. Although a macOS client app cannot happen until https://github.com/cashapp/sqldelight/pull/1393 is merged to SQLDelight, it'd be nice to atleast setup things in preparation of it.

**Comment by KerstinMaur** [comment]
Do you plan to add Linux too? 😊

**Comment by saket** [comment]
I wouldn't be against it, but I realistically don't see it happening anytime soon given my time constraints for a side project.
