### ISSUE TITLE
Cursor is not visible in Code block

### ISSUE THREAD

**Issue by drakeet** [saket/press#11]
| No text selected | Selected |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/5214214/70499564-655cba00-1b54-11ea-9f91-322017e09264.png) | ![image](https://user-images.githubusercontent.com/5214214/70499601-760d3000-1b54-11ea-86d4-d798078352b4.png)|

Happened on Samsung S9+ (Android 9)

**Comment by drakeet** [comment]
Pixel 3 (Android 10) can also reproduce:

<img src="https://user-images.githubusercontent.com/5214214/70500081-9db0c800-1b55-11ea-99a3-68527076d115.png" width=240 />

**Comment by saket** [comment]
Yea this seems to be an annoying behavior when [`BackgroundColorSpan`](https://developer.android.com/reference/android/text/style/BackgroundColorSpan) is used. It would be great to find a workaround.

**Comment by drakeet** [comment]
Try this way → [RoundedBgTextView.kt#L56](https://github.com/googlearchive/android-text/blob/996fdb65bbfbb786c3ca4e4e40b30509067201fc/RoundedBackground-Kotlin/lib/src/main/java/com/android/example/text/styling/roundedbg/RoundedBgTextView.kt#L56)

<img src="https://user-images.githubusercontent.com/5214214/70504779-706a1700-1b61-11ea-98f9-e41687a1a5a8.png" width=280/>
(I modified the color to Black to verify this issue)

- https://medium.com/androiddevelopers/drawing-a-rounded-corner-background-on-text-5a610a95af5

**Comment by saket** [comment]
That View draws custom background on the canvas directly instead of using spans, but maybe that's a good thing? Code blocks with rounded corners would be nice. Wanna send a PR?

**Comment by drakeet** [comment]
Sorry, I don't have enough time to do that recently. And there is another workaround that just use a translucent color as the block span bg, but this is not perfect, if we pursue perfection, the method created by @florina-muntenescu can do it. Hope you or someone can solve it one day.

**Comment by saket** [comment]
No problem. Turns out there's a far simpler solution: using a translucent color for the code background instead of an opaque one. I'll fix this soon. If someone's interested, feel free to send a PR.

**Comment by saket** [comment]
Done: https://github.com/saket/press/commit/12cc95592250e73b674c658d876d9cec00e572f6
