### ISSUE TITLE
Support save/restore state for HomeView/EditorView

### ISSUE THREAD

**Issue by eneim** [saket/press#12]
I see that you have not handled that save/restore state. If you are fine adding this logic, I will have a PR coming :D.

**Comment by saket** [comment]
Whoops yes, `HomeView` needs to save the state of its page. Go ahead!

**Comment by eneim** [comment]
@saket thanks. It may take a while. Below is my objective:

- [ ] For HomeView: restore editor state on config change: if it was in Editor mode, it will be in Editor mode after config change. Also, if it is restored to Editor mode after config change, `nodeList` will expand immediately for UX consistency.

- [ ] For EditorView (if HomeView is restored to Editor mode): it will restore the scroll position where user at before the config change *regarding the text line* (for example if in my long text, the 3rd H2 was on top of the editor before the config change, it should be on top of the editor after the config change if the text is long enough). The challenge is when the config change is due to an orientation change, text width is changed so a simple scroll position save/restore will not be enough.

I have started the implementation, but if you have any comment on the objective above let's discuss.

**Comment by saket** [comment]
For `HomeView`, this will be useful: https://github.com/saket/InboxRecyclerView/blob/70d0613c674d3f479072b6a84e23503af6241b69/inboxrecyclerview/src/main/java/me/saket/inboxrecyclerview/InboxRecyclerView.kt#L98. We'll just need to recreate an `EditorView` from `HomeView#onSaveInstanceState()`.

For `EditorView`, `ScrollView` should be capable of restoring the scroll position on its own. Try giving it an ID?

**Comment by eneim** [comment]
@saket Yeah the idea is to have ID for both HomeView and EditorView and then add the save/restore methods. The thing about EditorView is the same Scroll amount will scroll to different line of text in the editor I believe. Will double check for sure, but yeah we are on the same page about the concept I think.

**Comment by saket** [comment]
Closed via #31
