### ISSUE TITLE
Delete a note

### ISSUE THREAD

**Issue by hackertronix** [saket/press#13]
As of now, the only available option to delete a note is by deleting its content _(Or maybe there is another way but it's not promoted)._ 

Can we maybe add 🤔

-  Delete option within the editor
-  Select multiple notes in the main view and perform a batch delete/archive?

**Comment by saket** [comment]
Yea, gotta add a delete/archive button somewhere. About batch operations: have you ever felt the need to delete multiple notes at once?

**Comment by hackertronix** [comment]
That's a good question. Maybe not delete but I certainly archive notes a lot on Keep. I think swipe to delete/archive would be good. 

Can I maybe take a shot at it? The delete option from the editor view I mean  _(Will need some time to wrap my head around the project but would definitely want to try)_

**Comment by saket** [comment]
Of course, but let me think of UI controls on the note screen first? 

In the meantime, it would be a good idea to add `archivedAt` column to the note table to prepare for this. Wanna help me do that?

**Comment by hackertronix** [comment]
Yes 🤓

**Comment by eneim** [comment]
A *swipe to do something* would be a nice add regarding the UX is heavily gesture based.

**Comment by hackertronix** [comment]
Hey @saket , are the designs ready by any chance?

**Comment by saket** [comment]
Hey, nope. I've decided to avoid nerd sniping myself into completing the Android app. I'm focusing all my time into learning macOS development so that I can add a second platform to Press. Deleting a note is unintuitive, but is at-least possible.

**Comment by hackertronix** [comment]
Sounds fair. If you do however decide on adding that let me know 😉

**Comment by JakeWharton** [comment]
Note that deleting all the content does not delete the underlying file. Instead, you get a series of `untitled_note` files.

![Screen Shot 2020-11-02 at 3 53 57 PM](https://user-images.githubusercontent.com/66577/97918229-c882ac80-1d23-11eb-9134-30ca8f3e586d.png)

**Comment by saket** [comment]
Uhhh actually yeah that is true. Adding an archive/delete button is on my to-do list but that'll in-turn require support for folders first.

**Comment by saket** [comment]
I should also point out that Press will delete notes for real if they're deleted from your git repository. The functionality is just not exposed from the UI.

**Comment by saket** [comment]
Closed by #67. Will release as part of v1.8.
