### ISSUE TITLE
Explore C interop with Kotlin/Native for sharing a common markdown parser

### ISSUE THREAD

**Issue by saket** [saket/press#30]
Press currently delegates parsing of markdown to platforms using `expect/actual`, but managing the expected class signature of parsed nodes is a [pain right now](https://github.com/saket/press/blob/2f9f81fac8386aa8b8459a1d4b1aa919d851a32d/wysiwyg/src/commonMain/kotlin/me/saket/wysiwyg/parser/node/Node.kt#L20). The K/N community is new so there isn't any markdown parser written in kotlin, but there are sufficient libraries written in C that Press can leverage through C interop with K/N: https://kotlinlang.org/docs/reference/native/c_interop.html

We could use cmark: https://github.com/commonmark/cmark

**Comment by saket** [comment]
Assigning this to @hackertronix who's working on adding bindings for [cmark](https://github.com/commonmark/cmark).

@hackertronix I've added some basic tests on `saket/apr26/markdown-parser-test` to help you test your bindings.

Update: Huh, I can't assign people randomly to an issue. That probably makes sense. @hackertronix wanna assign this yourself?

**Comment by saket** [comment]
Huh, I can't assign people randomly to an issue. That probably makes sense. @hackertronix wanna assign this yourself?

**Comment by saket** [comment]
Actually, let me just disable those tests and merge them to master.

**Comment by hackertronix** [comment]
I am unable to assign it to myself :(

**Comment by saket** [comment]
Looks like someone has to comment before they can be assigned. Done!

**Comment by saket** [comment]
Turns out cinterop can only generate bindings for kotlin/native. We'll still have to use JNI for Android which sucks. I [filed a feature request](https://youtrack.jetbrains.com/issue/KT-39144) to support generation of bindings for all platforms but don't think that's going to happen anytime soon.

**Comment by saket** [comment]
Superseded by https://github.com/saket/press/issues/51
