### ISSUE TITLE
Detach Editor Code as Library?

### ISSUE THREAD

**Issue by ubarua123** [saket/press#53]
I think the work you're doing is fantastic. Keeping the editor code as a library would be perfect so that everyone can use it the way they want. 
I have scoured the internet and I couldn't find a decent Markdown editor until I came across your app. The only issue is, its a full app 😁  .
Do consider it.

**Comment by saket** [comment]
That's the plan! You can try using [wysiwyg](http://github.com/saket/wysiwyg) in the meantime but it's quite old and the improvements made as part of Press haven't been merged yet.

**Comment by ubarua123** [comment]
I'll be looking forward to your library then. 🙂

**Comment by ubarua123** [comment]
Any update on this? When can I integrate the updated version of the editor in my app?

**Comment by saket** [comment]
Nothing yet. I want to migrate wysiwyg to https://github.com/JetBrains/markdown so that it can become a multiplatform library.
