### ISSUE TITLE
Multiplatform git client

### ISSUE THREAD

**Issue by saket** [saket/press#61]
Having a git client that works on kotlin/native is necessary to implement sync on native platforms. I wasn't able to find any existing library, so Press will have to write [libgit2](https://github.com/libgit2/libgit2) of its own using cinterop. Kotlin has an official sample that can be used as a reference: https://github.com/JetBrains/kotlin-native/tree/master/samples/gitchurn

**Comment by jamiesanson** [comment]
Hey there, I'm interested in contributing and would love to help with this issue. I see you've already had a go at integrating `libgit2` under the saket/oct30/native-git branch. How far did you get with that? It looks like a quick spike. I'm happy to build upon that and can have a go at getting rid of the remaining `TODO()`s, but wary that you might have some learnings from that spike which haven't been captured here. 

I've been enjoying using Press on Android, and can't wait to end my Ulysses subscription. Let me know how I can help!

**Comment by saket** [comment]
Thanks for offering help @jamiesanson! I was trying to set it up but the announcement of Compose for building desktop apps have changed everything. Being able to use the same source-set for not only syncing files, but also parsing markdown on both Android and desktop sounds like a great thing and possibly the fastest way to get the desktop app up and running. 

Let me close this issue and create another one to track that.
