### ISSUE TITLE
Ordered lists doesn't auto complete

### ISSUE THREAD

**Issue by ChanSek** [saket/press#69]
If I am at an item of an ordered list, then pressing enter should show the next number of the list by default. But this happens only if your previous item ends wjth a period (.) symbol.

You can reproduce it by doing two below tests.

1. Type something <press enter>

vs

1. Type something. <press enter>

**Comment by saket** [comment]
Interesting. It works fine for me on a Pixel 3 and a Galaxy Fold 2:

https://user-images.githubusercontent.com/2387680/105622235-b887df80-5ddd-11eb-8395-7a12c32c5724.mp4

The tests for the text formatter ([AutoFormatOnEnterPressTest](https://github.com/saket/press/blob/11319204024186226182d253af0bc48cdd387633/wysiwyg/src/commonTest/kotlin/me/saket/wysiwyg/formatting/AutoFormatOnEnterPressTest.kt#L234:L247)) are passing just fine, so I suspect there's something weird happening with the way Press detects enter key presses on your phone/keyboard.

Can you help me debug this by placing a breakpoint here? https://github.com/saket/press/blob/18f1beba9d09f39514737ed9e9bbfee086ec2f12/androidApp/src/main/java/press/editor/EnterKeyPressListener.kt#L48

**Comment by ChanSek** [comment]
Looks like, there is some corner case which I am not able to find it right now. Will update if I am able to reproduce it.

For now, you can close the issue.

**Comment by manueldidonna** [comment]
> Looks like, there is some corner case which I am not able to find it right now. Will update if I am able to reproduce it.
> 
> For now, you can close the issue.

If you add a blank space before pressing enter it should works. I think it's related to the keyboard you used. I get this weird behavior while using the beta version of Gboard, the autocompletition works as expected with swiftkey and stable Gboard

**Comment by saket** [comment]
That is very useful information, thank you! I was able to reproduce this with gboard beta. Gotta rethink how Press detects enter key presses.

**Comment by saket** [comment]
Fixed by https://github.com/saket/press/commit/680850144cae864076b29a977567e34bb24819bd. Will release this as part of v1.8. Thanks @manueldidonna and @ChanSek!

**Comment by saket** [comment]
Released in v1.8: https://github.com/saket/press/releases/tag/v1.8
