### ISSUE TITLE
Possible freezing for Native

### ISSUE THREAD

**Issue by arkivanov** [saket/press#7]
Hey, I just wanted to bring your attention to the possible freezes (and crashes) when you will be implementing iOS. 

E.g. [here](https://github.com/saket/Press/blob/c5d9ae539cc1c65dd7cf45aff58962e1ee4c4acf/shared/src/commonMain/kotlin/me/saket/press/shared/editor/EditorPresenter.kt#L173
) presenter and/or repository will be frozen which might cause unexpected behaviour. Be ready to use `threadLocal` operator and/or `subscribe(isThreadLocal=true,...)`. Also `ensureNeverFrozen` might be useful.

**Comment by saket** [comment]
I realize I completely forgot about freezing of objects 🤦‍♂What would be a good way to add tests that run in an environment where K/N threading is tested?

> E.g. here presenter and/or repository will be frozen which might cause unexpected behaviour. Be ready to use threadLocal operator and/or subscribe(isThreadLocal=true,...). Also ensureNeverFrozen might be useful.

Is my understanding correct that I'm passing `noteRepository` inside a lambda that will run on another thread so it needs to be frozen?

```kotlin
noteRepository.note(noteId)
    .take(1)
    .mapToSome()
    .flatMapCompletable { note ->
      when {
        shouldDelete -> noteRepository.markAsDeleted(note.uuid)
        else -> noteRepository.update(note.uuid, content)
      }
    }
```

I remember looking at the addition of `threadLocal()`, but I didn't understand what it does. Does it have to do something with K/N's **relaxed** memory model?

**Comment by arkivanov** [comment]
Just put `threadLocal` before top most callback with capturing lambda and make sure you are building observables on main thread. Reaktive is very good here. Use `ensureNeverFrozen` on presenters and their dependencies and use `TestScheduler`, `TestObservable` and `Observable.test` extension function. They freeze things by default and you will catch all the bugs.

**Comment by arkivanov** [comment]
Unless you really need to use dependencies on background thread. In this case they must be designed that way (without any mutable state).

**Comment by arkivanov** [comment]
I will pull-request some fixes today

**Comment by arkivanov** [comment]
Unfortunately I'm unable to do that. I'm using Ubuntu and can't verify my PR. Will pull request after #14.

**Comment by saket** [comment]
> Unless you really need to use dependencies on background thread. In this case they must be designed that way (without any mutable state).

The presenter and the repository don't hold any mutable class properties. In that case, will it be okay if they get frozen? Will local variables in functions need explicit freezing?

> Just put threadLocal before top most callback with capturing lambda and make sure you are building observables on main thread.

Got it. In case `EditorPresenter` starts holding mutable state and cannot be frozen, would [this line](https://github.com/saket/Press/blob/74ee1b6f3bd2356c4d1221b0495daca219196478/shared/src/commonMain/kotlin/me/saket/press/shared/editor/EditorPresenter.kt#L151) be the right place to put `threadLocal()`?

> I will pull-request some fixes today

Much appreciated, thank you. #14 was merged so tests can now run, but they run on the JVM. Discussing it in #3.

**Comment by arkivanov** [comment]
> The presenter and the repository don't hold any mutable class properties. In that case, will it be okay if they get frozen? Will local variables in functions need explicit freezing?

It will be ok. At the moment it appears to be safe since all the captured objects are safe to freeze. But I would prefer to avoid freezes.

> Got it. In case EditorPresenter starts holding mutable state and cannot be frozen, would this line be the right place to put threadLocal()?

No, you have to put `threadLocal` right before [this](https://github.com/saket/Press/blob/74ee1b6f3bd2356c4d1221b0495daca219196478/shared/src/commonMain/kotlin/me/saket/press/shared/editor/EditorPresenter.kt#L171) line. Also you can remove [this](https://github.com/saket/Press/blob/74ee1b6f3bd2356c4d1221b0495daca219196478/shared/src/commonMain/kotlin/me/saket/press/shared/editor/EditorPresenter.kt#L152) line. I will do it in a PR.

> Much appreciated, thank you. #14 was merged so tests can now run, but they run on the JVM. Discussing it in #3.

Waiting for iOS tests, thanks

**Comment by arkivanov** [comment]
Please read the last comment in #19
