### ISSUE TITLE
Setup a blank iOS app

### ISSUE THREAD

**Issue by saket** [saket/press#9]
Just getting a blank iOS app running would be a good first step towards bringing Press to iOS. Everything else can be wired later.

**Comment by riteshhgupta** [comment]
Hey @saket 👋 You can assign it to me, I would be happy to kickstart the iOS platform :)

**Comment by saket** [comment]
Done! 🤟

**Comment by saket** [comment]
Fwiw the Kotlin slack team is a treasure of information. I imagine integrating Kotlin multiplatform with iOS won't be as smooth as Android. You might find help if you run into roadblocks: http://slack.kotlinlang.org/

**Comment by ncooke3** [comment]
hey there @saket ! I'd be interested in helping with iOS too! Been looking for a a way to start contributing to open source and this project looks awesome! how can I help?

**Comment by saket** [comment]
Thank you @ncooke3! There is a directory for the iOS app but it's empty right now. If we could get it up running and just print the name of the saved notes, that would be dope. 

The database table can be accessed using a `NoteQueries` file that will be generated when the project is built. You can get a reference to it as shown here: https://github.com/saket/press/blob/493645450944a2d94246807721afb8b7ebb93f07/shared/src/commonMain/kotlin/me/saket/press/shared/db/SharedDatabaseComponent.kt#L14

**Comment by saket** [comment]
If you're feeling adventurous, printing the list of notes using [HomePresenter](https://github.com/saket/press/blob/master/shared/src/commonMain/kotlin/me/saket/press/shared/home/HomePresenter.kt) instead of directly accessing the database classes would a huuuge win. In case it's useful, you can see how the presenter is used in [HomeView here](https://github.com/saket/press/blob/844e8f5f156c7f60bf8c6a857b91bf628852f6ee/androidApp/src/main/java/press/home/HomeView.kt#L129).

The shared code uses [reaktive](https://github.com/badoo/Reaktive), which offers [interop functions](https://github.com/badoo/Reaktive/blob/e3c178e6e923ead19ef00758b889c1f4526c864f/rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Observable.kt) with RxJava for Android. I _think_ adding interop for something that's common on Swift (do you use RxSwift?) won't be too hard.

**Comment by saket** [comment]
Btw @ncooke3, please coordinate with @riteshhgupta?

**Comment by riteshhgupta** [comment]
Sorry folks @saket @ncooke3, pretty hectic week so couldn't start anything on it yet.  
@ncooke3 If you have ideas on how to initiate it then please go with it, I'll join you early next week.

**Comment by arkivanov** [comment]
A sample iOS app can be found [here](https://github.com/badoo/Reaktive/tree/master/sample-ios-app)

**Comment by arkivanov** [comment]
Looks like there is already a blank iOS app in the [iosApp](https://github.com/saket/press/tree/trunk/iosApp) folder?

**Comment by saket** [comment]
Yeah… I don't know if it works anymore. I think I'm going to close this issue for now. Getting a basic macOS app up and running is my first priority after Android.
